development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rampita_api_development
  pool:     5
  username: postgres
  password: postgres

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rampita_api_test
  pool:     5
  username: postgres
  password: postgres

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: rampita_api_production
  pool:     5
  username: postgres
  password: postgres
